### ISSUE TITLE
CREATE and UPDATE buttons unresponsive

### ISSUE THREAD

**Issue by eco-tiffanylin** [andywu123/AdminLanding#1]
For IE9:
The [Create] button is unresponsive when user tries to add a new record.
The [Update] button is unresponsive when the user tries to edit an existing record.

**Comment by TU-MinW** [comment]
Create is working well. Update is related to Image uploading. Need to talk with John later.

**Comment by TU-MinW** [comment]
Issue fixed. 
CHANGE
$('.btn-new-file input[type=file]').fileupload({
TO
$('.btn-new-linkfile input[type=file]').fileupload({

Make sure the name is unique.

**Comment by eco-tiffanylin** [comment]
Works!
