### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by eco-tiffanylin** [andywu123/AdminLanding#10]
Under Content Keywords, there is a typo on the word KEYWORD in the second column '# OF KEYWORDS' 
![content-keyword-misspelling](https://cloud.githubusercontent.com/assets/13125161/8703658/6c2b3058-2aec-11e5-88cc-ea59a4072b7b.jpg)

**Comment by andywu123** [comment]
fixed need to be updated

files changed: createkeyword.cshtml

**Comment by eco-tiffanylin** [comment]
The second column title is still misspelled as: # OF KEYWRODS

Please fix this. It should read: # OF KEYWORDS

**Comment by eco-tiffanylin** [comment]
Fixed!
