### ISSUE TITLE
Columns and rows should indicate clickability

### ISSUE THREAD

**Issue by eco-tiffanylin** [andywu123/AdminLanding#11]
Currently, when user hovers over a column or row in the data table, there is no indication that the column or row is clickable. This can be remedied by 1) changing the cursor to the pointer finger on columns and rows that are clickable, and 2) providing hover/select colors. 

Here are suggested colors for columns/rows:

![image](https://cloud.githubusercontent.com/assets/13125161/8704047/9c90166c-2aee-11e5-8e30-beba990cbe06.png)

Additionally, the columns should display with up and down arrows depending on which column is selected for sorting.

**Comment by andywu123** [comment]
fixed, need to be updated 
file changed: site.css

**Comment by eco-tiffanylin** [comment]
Fix looks good for the most part. One thing missing is the up/down arrow next to the column being sorted to indicate which direction the column is being sorted. 

Let me know if you need icon image provided.

**Comment by eco-tiffanylin** [comment]
![down](https://cloud.githubusercontent.com/assets/13125161/8730293/eee6d408-2bbd-11e5-865e-131c6bf43d2e.png)

![up](https://cloud.githubusercontent.com/assets/13125161/8730294/eee774f8-2bbd-11e5-8e67-fc4739866945.png)

**Comment by TU-MinW** [comment]
I think we may need icon image for sorting

**Comment by TU-MinW** [comment]
![sorting](https://cloud.githubusercontent.com/assets/13125065/8733488/0cdc3b92-2bd2-11e5-9fd9-1ab75dcfdcc8.GIF)

**Comment by eco-tiffanylin** [comment]
Can you move the arrow next to the column title so it looks like: TAG NAME ^

**Comment by TU-MinW** [comment]
Can we put it on the left side? Seems easy to achieve it. 

![left center](https://cloud.githubusercontent.com/assets/13125065/8734071/78cac38e-2bd5-11e5-910e-68acfa1ccccf.GIF)

**Comment by eco-tiffanylin** [comment]
What does that look like on a middle column?

**Comment by TU-MinW** [comment]
![middle](https://cloud.githubusercontent.com/assets/13125065/8734194/635c2370-2bd6-11e5-8477-90c835d6986a.GIF)

**Comment by eco-tiffanylin** [comment]
Ok that works. Can you give the highlight color a few more pixels on the left so that the arrow isn't right up against it?

**Comment by TU-MinW** [comment]
![pixel](https://cloud.githubusercontent.com/assets/13125065/8734679/86b0f456-2bd9-11e5-92aa-e954cbf48ea1.GIF)

**Comment by eco-tiffanylin** [comment]
Looks good, Min!
