### ISSUE TITLE
Confusing colors in Delete confirmation popup

### ISSUE THREAD

**Issue by eco-tiffanylin** [andywu123/AdminLanding#12]
Currently, when user attempts to delete a record, the following pop up displays:

![yes-no-color](https://cloud.githubusercontent.com/assets/13125161/8704117/156be624-2aef-11e5-8afa-747f4e269983.jpg)

YES is labeled red and NO is labeled green, which makes sense logically as YES will delete the record. However, intuitively this can be confusing to the user. Rather than switching colors and using Yes/No, we should just provide Delete and Cancel buttons. Delete should be red, while Cancel should just be default gray button color. This will draw attention to the severity of Delete without causing confusion.

**Comment by andywu123** [comment]
Fixed, need to be updated 

Files changed: confirmationModdal.cshtml

**Comment by eco-tiffanylin** [comment]
Issue resolved. Fix looks good!
