### ISSUE TITLE
Layout issues when screen is resized

### ISSUE THREAD

**Issue by eco-tiffanylin** [andywu123/AdminLanding#13]
For categories where the View/Edit page includes Add/Remove boxes (Content Tags and Content Keywords), the layout does not react well to screen resize. 

![image](https://cloud.githubusercontent.com/assets/13125161/8704567/be545288-2af1-11e5-8766-be9b35a9f881.png)

**Comment by andywu123** [comment]
Fixed, need to be updated 

Files Updated: site.css

**Comment by eco-tiffanylin** [comment]
Much better. 

It may not be the best approach for the boxes to be stacked should the user have to use the application on a small screen often since the elements are being moved from left to right, but for the time being this fix will do.
