### ISSUE TITLE
View/Edit Link Content

### ISSUE THREAD

**Issue by eco-tiffanylin** [andywu123/AdminLanding#15]
[Update] button does not work for Link Content even when user does not edit the Icon Image field.

**Comment by andywu123** [comment]
Other than image upload, fixed and updated 

files changed: flinkcont.js

**Comment by eco-tiffanylin** [comment]
Looks good! 

One thing: When the user changes the Icon Image then clicks [Update], a pop up window saying the Link Content has been updated pops up briefly and disappears before returning the user to the data table. Can we get rid of that pop up since it doesn't show up on any other page?

**Comment by eco-tiffanylin** [comment]
Fix looks good!
