### ISSUE TITLE
New Tag validation

### ISSUE THREAD

**Issue by eco-tiffanylin** [andywu123/AdminLanding#16]
[Create] button is unresponsive for NEW TAG when the user enters more than 1 character for the Abbreviation field. Even though the hint (1 character) is displayed, it is not enough to let the user understand the issue when the [Create] button is unresponsive. 

Two possible solutions:
1) Put a limit on the number of characters they can type in the Abbreviation field. After 1 character, the user cannot type any more characters. 
2) Upon click of [Create] button, if the Abbreviation field exceeds 1 character, display text that reads: Field cannot exceed 1 character.

**Comment by TU-MinW** [comment]
Added validation
![tagvalidation](https://cloud.githubusercontent.com/assets/13125065/8732033/f19da7a2-2bc8-11e5-8198-b3d0b15cf038.GIF)

**Comment by eco-tiffanylin** [comment]
@TU-MinW, does that red text show up only when the user attempts to [Create] without completing the fields?

**Comment by eco-tiffanylin** [comment]
Issue resolved!
