### ISSUE TITLE
Long text inputs causes unresponsive CREATE button

### ISSUE THREAD

**Issue by eco-tiffanylin** [andywu123/AdminLanding#2]
In Chrome:
When users enter a long string of text in the text fields, they cannot create a new record.

No indication of max length or errors are displayed when this occurs. The [Create] button just appears unresponsive.

**Comment by TU-MinW** [comment]
Caused by image uploading. Nothing about long text inputs.

**Comment by eco-tiffanylin** [comment]
That's interesting. I was able to Create a new record with image. Then I tried exact same thing but with longer text inputs and that was when the Create new failed to work.

**Comment by TU-MinW** [comment]
Can you try it again? And for which field you tried longer text inputs but failed?

**Comment by eco-tiffanylin** [comment]
Does not work if Title is long.

**Comment by eco-tiffanylin** [comment]
Seems like it won't work over 100 characters.

**Comment by eco-tiffanylin** [comment]
Confirmed: If TITLE field is over 100 characters, the Create and Update buttons will not work.

**Comment by eco-tiffanylin** [comment]
The validation message should display two separate messages depending on the validation issue:

1) This field is required.

2) This field cannot be over 100 characters. 
- For the required fields, the title should be marked with a red \* or red text that reads (Required) .
- For the number of characters, we should include a character count so the user is aware how many more characters they have left.

**Comment by TU-MinW** [comment]
![pics](https://cloud.githubusercontent.com/assets/13125065/8728019/efa89668-2bb0-11e5-8090-73619de28f63.GIF)

**Comment by eco-tiffanylin** [comment]
Can you place the \* before the :?
Also since that doesn't say Required, we would need to include a note on the page that says:

*indicates required fields

**Comment by TU-MinW** [comment]
Where do you want to include the note? Under the NEW ANNOUNCEMENT ? Or next the Cancel Button ?

![landingantitle](https://cloud.githubusercontent.com/assets/13125065/8728887/c26f890e-2bb5-11e5-8def-7b9bf18a8c9c.GIF)

**Comment by eco-tiffanylin** [comment]
Above the first field. Left aligned.  Have the message read:

Required field(s) are indicated by an *

**Comment by TU-MinW** [comment]
![note](https://cloud.githubusercontent.com/assets/13125065/8729078/f8f0f87c-2bb6-11e5-9055-896fda9ae9fd.GIF)

**Comment by eco-tiffanylin** [comment]
That looks good!

**Comment by eco-tiffanylin** [comment]
Actually, can you change the text to black and just have the \* in red so it matches the titles?

**Comment by TU-MinW** [comment]
![final](https://cloud.githubusercontent.com/assets/13125065/8729692/927588d4-2bba-11e5-8d3a-7ac459bf5da8.GIF)
Good?

**Comment by eco-tiffanylin** [comment]
Perfect!
