### ISSUE TITLE
Tag Color validation

### ISSUE THREAD

**Issue by eco-tiffanylin** [andywu123/AdminLanding#21]
Since users can only enter a 6 character long hex color code for the Tag Color and Text Color, we should include the hint (hex) with the title. For example:

Tag Color (hex):
Text Color (hex):

We should also place a # in front of the text box to help give context clues to the user.

![image](https://cloud.githubusercontent.com/assets/13125161/8732602/962d781c-2bcc-11e5-89ae-3e7cffdd2672.png)

**Comment by TU-MinW** [comment]
![tagcolor](https://cloud.githubusercontent.com/assets/13125065/8733116/da993682-2bcf-11e5-9f0f-7e926f48a916.GIF)
Does it look good?

**Comment by eco-tiffanylin** [comment]
Looks great!

**Comment by eco-tiffanylin** [comment]
The character count and limit works great. Really helps improve usability.
