### ISSUE TITLE
Layout - Content Keywords

### ISSUE THREAD

**Issue by TU-MinW** [andywu123/AdminLanding#27]
Add search box for two small tables.

**Comment by andywu123** [comment]
Fixed,

files changed: contentkeyword.js

**Comment by TU-MinW** [comment]
Search box is not working. 
![search](https://cloud.githubusercontent.com/assets/13125065/8834717/f1d4010c-3083-11e5-89d7-8e93dd599912.GIF)

![searched](https://cloud.githubusercontent.com/assets/13125065/8834721/f4cc0b98-3083-11e5-8b9e-c27cec3468f2.GIF)

**Comment by TU-MinW** [comment]
Same issue in [View/Edit] Content Tags
