### ISSUE TITLE
Delete does not reflect until page refresh

### ISSUE THREAD

**Issue by eco-tiffanylin** [andywu123/AdminLanding#4]
In Chrome:
When user deletes a record, the record remains in the data table until the user refreshes their page.
This is not a consistent issue. For every third delete, the system is immediately responsive to the delete without user refreshing the page. However, on the next delete, the system is once again unresponsive until the user refreshes the page.

**Comment by andywu123** [comment]
Fixed, need to be updated 

Files changed: Announcement.js delete function

**Comment by andywu123** [comment]
Still need to work on it.

**Comment by eco-tiffanylin** [comment]
Issue resolved.
