### ISSUE TITLE
Display issue - View/Edit in Content Keywords

### ISSUE THREAD

**Issue by eco-tiffanylin** [andywu123/AdminLanding#5]
In Chrome:
When user selects to show a larger number of entries, the additional entries are displayed over the bounding box and the [Save[ and [Cancel] buttons. 

![show-100](https://cloud.githubusercontent.com/assets/13125161/8702582/9905a3ac-2ae6-11e5-853d-23b882beeef0.jpg)

**Comment by andywu123** [comment]
Fixed need to be updated. 
Files Changes: site.css

**Comment by eco-tiffanylin** [comment]
Fix looks good.
