### ISSUE TITLE
NEW Link Content 

### ISSUE THREAD

**Issue by eco-tiffanylin** [andywu123/AdminLanding#7]
In Chrome:
When user clicks [Create] upon attempt to create a NEW LINK CONTENT, the system returns a pop up that displays:

"CREATE COMPLETE 
Link Content is created"

The application then remains on the same NEW LINK CONTENT page rather than returning the user to the main Link Contents page. This causes confusion as the user cannot see that their newly created Link Content has in fact been added, and they cannot select further functions relating to Link Contents unless they click Link Contents on the left-side menu to return to the page. 

The only options the users have on the page are the [Create] and [Cancel] buttons which can result in two issues:
- Duplicates of the same Link Content being created if the user continues to click the [Create] button trying to get a response from the system.
- Frustration when they click [Cancel] and think their new entry was not created.
  ![new link content](https://cloud.githubusercontent.com/assets/13125161/8702900/74cd0bb8-2ae8-11e5-9287-bdfe16035f6e.jpg)

**Comment by TU-MinW** [comment]
I add "window.open(siteBaseUrl + "LinkCont/LinkContents", "_self"); " to make the page redirect to home page after create a new record.  
-----However, if creating a new record without image uploading, it still encounter an issue.

**Comment by TU-MinW** [comment]
LinkContent.js changed

**Comment by eco-tiffanylin** [comment]
The Icon Image field seems to be acting as a required field. There is no indication to the user that it is a required field but the [Create] button is unresponsive unless an Icon Image has been selected.

**Comment by andywu123** [comment]
Fixed and updated other than image

Files updated: linkcont.js

**Comment by eco-tiffanylin** [comment]
Looks good!
