### ISSUE TITLE
NEW Interesting Content

### ISSUE THREAD

**Issue by eco-tiffanylin** [andywu123/AdminLanding#8]
In Chrome:
- When user selects an Application, error message displays. 
- Content picklist is not populated for user to select and therefore user cannot [Create] a NEW Interesting Content.

![interesting-content-error](https://cloud.githubusercontent.com/assets/13125161/8703025/26e64ea4-2ae9-11e5-84f7-18fd8fa69276.jpg)
![empty field](https://cloud.githubusercontent.com/assets/13125161/8703024/26e28c4c-2ae9-11e5-8638-3b83072a8a56.jpg)

**Comment by andywu123** [comment]
Fixed, need to be updated
files changed: interestingcontent.js

**Comment by eco-tiffanylin** [comment]
Issue resolved.
