### ISSUE TITLE
Labeling consistencies

### ISSUE THREAD

**Issue by eco-tiffanylin** [andywu123/AdminLanding#9]
The labels and titles should be consistent when it comes to singular/plural use. The title in the left-side menu should be the same as the title in the right section. Both of these should be plural. Therefore the following changes need to be made:
- In the left-side menu:
  1) 'Announcement' (current) should be 'Announcements'
  2) 'Search/ Search Relation' (current) should be 'Search/Search Relations'. Please note the spacing between the words and the / mark.
- For sections with +New options, the following changes need to be made:
  1) In 'NEW ANNOUNCEMENTS', the title should be a singular 'NEW ANNOUNCEMENT' as user will only be adding one announcement at a time.
  2) In Interesting Contents, it currently reads 'NEW' but it should be 'NEW INTERESTING CONTENT'
- For sections with Edit or View/Edit options:
  1) In Edit Announcements, 'ANNOUNCEMENTS' should be 'ANNOUNCEMENT' (singular)  
  2) In Edit Content Tags, 'CONTENT NAME: ____' should be 'CONTENT TAG: ____' 
  3) In Edit Content Keywords, 'CONTENT NAME: ____' should be 'CONTENT KEYWORD: _____'
  4) In Edit Link Contents, 'LINK CONTENTS' should be 'LINK CONTENT' (singular)
  5) In Edit Keywords, 'KEYWORDS' should be 'KEYWORD'
  6) In Edit Tags, 'TAGS' should be 'TAG'

**Comment by TU-MinW** [comment]
•In the left-side menu:  Menu.cshtml 
•For sections with +New options, the following changes need to be made:
Views/Home/Create.cshtml
Views/InstCont/CreateInstCont.cshtml
•For sections with Edit or View/Edit options:
Views/Home/Create.cshtml
Views/ContTag/ContentTags
Views/ContKeyword/ContKeyword.cshtml
Views/LinkCont/CreateLinkCont.cshtml
Views/Keyword/CreateKeyword.cshtml
Views/Tag/CreateTag.cshtml

**Comment by eco-tiffanylin** [comment]
Issue resolved. Labels look good!
